services:
  insertion_sort:
    build:
      context: .
      dockerfile: src/insertion_sort/Dockerfile
    volumes:
      - ./src:/app/src 
    command: ["./build/main"]
  
  selection_sort:
    build:
      context: .
      dockerfile: src/selection_sort/Dockerfile
    volumes:
      - ./src:/app/src 
    command: ["./build/main"]
    depends_on:
      - insertion_sort 
  
  bubble_sort:
    build:
      context: .
      dockerfile: src/bubble_sort/Dockerfile
    volumes:
      - ./src:/app/src
    command: ["./build/main"]
    depends_on:
      - selection_sort
